#!/bin/bash

if test $# -lt 1
then
	echo "Usage: $0 python_script_file_using_ftk"
	exit 1
fi

export PYTHONPATH=${PWD}:${PYTHONPATH}
if test -x ${1}
then
	path=${1}
	if test "${path:0:5}" = "test/"
	then
		pushd "test" >/dev/null
		cmd="./${path:5}"
	elif test "${path:0:7}" = "./test/"
	then
		pushd "test" >/dev/null
		cmd="./${path:7}"
	else
		cmd="./${path}"
	fi

	shift 1

	echo "***************************************"
	echo "run ${path}"
	echo "***************************************"
	exec ${cmd} $@
fi
