#!/usr/bin/env python

'''Constants and enums for all ftk submodules.
'''

__docformat__ = 'restructuredtext'
__version__ = '$Id: $'

#BEGIN GENERATED CONSTANTS; see support/make_constants.py

# enum from ftk_list_model_default.h
# enum _FtkListItemType
(FTK_LIST_ITEM_NORMAL,
	FTK_LIST_ITEM_RADIO,
	FTK_LIST_ITEM_CHECK,
	FTK_LIST_ITEM_MORE) = range(0, 4)

# enum from ftk_canvas.h
# enum _FtkBgStyle
(FTK_BG_NORMAL,
	FTK_BG_TILE,
	FTK_BG_CENTER,
	FTK_BG_FOUR_CORNER) = range(0, 4)

# enum from ftk_file_browser.h
# enum _FtkFileBrowserType
(FTK_FILE_BROWER_APP,
	FTK_FILE_BROWER_SINGLE_CHOOSER,
	FTK_FILE_BROWER_MULTI_CHOOSER) = range(0, 3)

# constants from ftk_icon_view.h
FTK_ICON_VIEW_ITEM_SIZE = 64
FTK_ICON_VIEW_ITEM_MIN = 32
FTK_ICON_VIEW_ITEM_MAX = 240

# constants from ftk_typedef.h
FTK_KEY_LEN = 31
FTK_VALUE_LEN = 63
FTK_IM_WORD_LENGTH = 31
FTK_IM_RAW_TEXT_LENGTH = 31
FTK_IM_CANDIDATE_BUFF_LENGTH = 1023
FTK_H_MARGIN = 3
FTK_V_MARGIN = 3
FTK_MAX_PATH = 260
FTK_MAX_WINDOWS = 32
FTK_SPACE_WIDTH = 5
FTK_MAX_IMAGE_DECODERS = 6
FTK_STATUS_PANEL_HEIGHT = 36
FTK_DIALOG_BORDER = 2
FTK_DIALOG_TITLE_HEIGHT = 32
FTK_SCROLL_BAR_WIDTH = 10
FTK_MENU_MAX_ITEM = 16
FTK_MENU_ITEM_HEIGHT = 48
FTK_MENU_ITEM_WIDTH = 100
FTK_POPUP_MENU_ITEM_HEIGHT = 40
FTK_STOCK_IMG_SUFFIX = ".png"
FTK_LABEL_LEFT_MARGIN = 3
FTK_LABEL_TOP_MARGIN = 1
FTK_CLIPBOARD_SIZE = 1024
FTK_TITLE_LENGTH = 15
FTK_IM_PREEDITOR_MAX_ROW = 5
FTK_TAB_WIDTH = 4
FTK_FONT_SIZE = 16
ZERO_LEN_ARRAY = 0

# enum from ftk_typedef.h
# enum _FtkBool
FTK_TRUE = 1
FTK_FALSE = 0
# enum _Ret
(RET_OK,
	RET_FAIL,
	RET_REMOVE,
	RET_CONTINUE,
	RET_FOUND,
	RET_EOF,
	RET_NEXT,
	RET_QUIT,
	RET_EXIST,
	RET_AGAIN,
	RET_IGNORED,
	RET_NO_TARGET,
	RET_NOT_FOUND,
	RET_OUT_OF_SPACE) = range(0, 14)
# enum _FtkMarqueeAttr
FTK_MARQUEE_NONE = 0
FTK_MARQUEE_AUTO = 1
FTK_MARQUEE_ALWAYS = 2
FTK_MARQUEE_ONCE = 4
FTK_MARQUEE_FOREVER = 8
FTK_MARQUEE_DOWN2UP = 16
FTK_MARQUEE_RIGHT2LEFT = 32
# enum _FtkAlignment
(FTK_ALIGN_LEFT,
	FTK_ALIGN_RIGHT,
	FTK_ALIGN_CENTER) = range(0, 3)
# enum _FtkPixelFormat
(FTK_PIXEL_NONE,
	FTK_PIXEL_BGR24,
	FTK_PIXEL_BGRA32,
	FTK_PIXEL_RGB565,
	FTK_PIXEL_RGBA32) = range(0, 5)
# enum _FtkWidgetType
(FTK_WIDGET_NONE,
	FTK_WINDOW,
	FTK_DIALOG,
	FTK_WINDOW_MISC,
	FTK_STATUS_PANEL,
	FTK_MENU_PANEL,
	FTK_MENU_ITEM,
	FTK_LABEL,
	FTK_BUTTON,
	FTK_IMAGE,
	FTK_ENTRY,
	FTK_PAINTER,
	FTK_WAIT_BOX,
	FTK_STATUS_ITEM,
	FTK_PROGRESS_BAR,
	FTK_RADIO_GROUP,
	FTK_RADIO_BUTTON,
	FTK_CHECK_BUTTON,
	FTK_SCROLL_VBAR,
	FTK_SCROLL_HBAR,
	FTK_LIST_VIEW,
	FTK_ICON_VIEW,
	FTK_TEXT_VIEW,
	FTK_COMBO_BOX,
	FTK_TAB,
	FTK_TAB_PAGE,
	FTK_WIDGET_TYPE_NR) = range(0, 27)
# enum _FtkLogLevel
(FTK_LOG_V,
	FTK_LOG_D,
	FTK_LOG_I,
	FTK_LOG_W,
	FTK_LOG_E) = range(0, 5)
# enum _FtkWidgetState
(FTK_WIDGET_NORMAL,
	FTK_WIDGET_FOCUSED,
	FTK_WIDGET_ACTIVE,
	FTK_WIDGET_INSENSITIVE,
	FTK_WIDGET_STATE_NR) = range(0, 5)
# enum _FtkWidgetAttr
FTK_ATTR_TRANSPARENT = 1
FTK_ATTR_NO_FOCUS = 2
FTK_ATTR_BG_CENTER = 4
FTK_ATTR_BG_TILE = 8
FTK_ATTR_BG_FOUR_CORNER = 16
FTK_ATTR_INSENSITIVE = 32
FTK_ATTR_FOCUSED = 64
FTK_ATTR_IGNORE_CLOSE = 128
FTK_ATTR_QUIT_WHEN_CLOSE = 256
FTK_ATTR_AUTO_LAYOUT = 512
FTK_ATTR_POPUP = 1024
# enum _FtkRotate
(FTK_ROTATE_0,
	FTK_ROTATE_90,
	FTK_ROTATE_180,
	FTK_ROTATE_270,
	FTK_ROTATE_NR) = range(0, 5)
# enum _FtkWrapMode
(FTK_WRAP_NONE,
	FTK_WRAP_CHAR,
	FTK_WRAP_WORD,
	FTK_WRAP_NR) = range(0, 4)

# constants from ftk_icon_cache.h
FTK_ICON_PATH_NR = 3
FTK_ICON_CACHE_MAX = 64

# constants from ftk_file_system.h
FTK_MIME_TYPE_LEN = 31

# enum from ftk_key.h
# enum _FtkKey
FTK_KEY_SPACE = 32
FTK_KEY_EXCLAM = 33
FTK_KEY_QUOTEDBL = 34
FTK_KEY_NUMBERSIGN = 35
FTK_KEY_DOLLAR = 36
FTK_KEY_PERCENT = 37
FTK_KEY_AMPERSAND = 38
FTK_KEY_APOSTROPHE = 39
FTK_KEY_QUOTERIGHT = 39
FTK_KEY_PARENLEFT = 40
FTK_KEY_PARENRIGHT = 41
FTK_KEY_ASTERISK = 42
FTK_KEY_PLUS = 43
FTK_KEY_COMMA = 44
FTK_KEY_MINUS = 45
FTK_KEY_PERIOD = 46
FTK_KEY_SLASH = 47
FTK_KEY_0 = 48
FTK_KEY_1 = 49
FTK_KEY_2 = 50
FTK_KEY_3 = 51
FTK_KEY_4 = 52
FTK_KEY_5 = 53
FTK_KEY_6 = 54
FTK_KEY_7 = 55
FTK_KEY_8 = 56
FTK_KEY_9 = 57
FTK_KEY_COLON = 58
FTK_KEY_SEMICOLON = 59
FTK_KEY_LESS = 60
FTK_KEY_EQUAL = 61
FTK_KEY_GREATER = 62
FTK_KEY_QUESTION = 63
FTK_KEY_AT = 64
FTK_KEY_A = 65
FTK_KEY_B = 66
FTK_KEY_C = 67
FTK_KEY_D = 68
FTK_KEY_E = 69
FTK_KEY_F = 70
FTK_KEY_G = 71
FTK_KEY_H = 72
FTK_KEY_I = 73
FTK_KEY_J = 74
FTK_KEY_K = 75
FTK_KEY_L = 76
FTK_KEY_M = 77
FTK_KEY_N = 78
FTK_KEY_O = 79
FTK_KEY_P = 80
FTK_KEY_Q = 81
FTK_KEY_R = 82
FTK_KEY_S = 83
FTK_KEY_T = 84
FTK_KEY_U = 85
FTK_KEY_V = 86
FTK_KEY_W = 87
FTK_KEY_X = 88
FTK_KEY_Y = 89
FTK_KEY_Z = 90
FTK_KEY_BRACKETLEFT = 91
FTK_KEY_BACKSLASH = 92
FTK_KEY_BRACKETRIGHT = 93
FTK_KEY_ASCIICIRCUM = 94
FTK_KEY_UNDERSCORE = 95
FTK_KEY_QUOTELEFT = 96
FTK_KEY_GRAVE = 96
FTK_KEY_a = 97
FTK_KEY_b = 98
FTK_KEY_c = 99
FTK_KEY_d = 100
FTK_KEY_e = 101
FTK_KEY_f = 102
FTK_KEY_g = 103
FTK_KEY_h = 104
FTK_KEY_i = 105
FTK_KEY_j = 106
FTK_KEY_k = 107
FTK_KEY_l = 108
FTK_KEY_m = 109
FTK_KEY_n = 110
FTK_KEY_o = 111
FTK_KEY_p = 112
FTK_KEY_q = 113
FTK_KEY_r = 114
FTK_KEY_s = 115
FTK_KEY_t = 116
FTK_KEY_u = 117
FTK_KEY_v = 118
FTK_KEY_w = 119
FTK_KEY_x = 120
FTK_KEY_y = 121
FTK_KEY_z = 122
FTK_KEY_LEFTBRACE = 123
FTK_KEY_OR = 124
FTK_KEY_RIGHTBRACE = 125
FTK_KEY_NOT = 126
FTK_KEY_DOT = 46
FTK_KEY_HOME = 65360
FTK_KEY_LEFT = 65361
FTK_KEY_UP = 65362
FTK_KEY_RIGHT = 65363
FTK_KEY_DOWN = 65364
FTK_KEY_PRIOR = 65365
FTK_KEY_PAGEUP = 65365
FTK_KEY_NEXT = 65366
FTK_KEY_PAGEDOWN = 65366
FTK_KEY_END = 65367
FTK_KEY_BEGIN = 65368
FTK_KEY_INSERT = 65379
FTK_KEY_ENTER = 65293
FTK_KEY_TAB = 65289
FTK_KEY_ESC = 65307
FTK_KEY_RIGHTCTRL = 65508
FTK_KEY_LEFTCTRL = 65507
FTK_KEY_RIGHTALT = 65514
FTK_KEY_LEFTALT = 65513
FTK_KEY_RIGHTSHIFT = 65506
FTK_KEY_LEFTSHIFT = 65505
FTK_KEY_DELETE = 65535
FTK_KEY_F1 = 65470
FTK_KEY_F2 = 65471
FTK_KEY_F3 = 65472
FTK_KEY_RETURN = 65472
FTK_KEY_F4 = 65473
FTK_KEY_F5 = 65474
FTK_KEY_F6 = 65475
FTK_KEY_F7 = 65476
FTK_KEY_F8 = 65477
FTK_KEY_F9 = 65478
FTK_KEY_F10 = 65479
FTK_KEY_CAPSLOCK = 65509
FTK_KEY_BACKSPACE = 65288
FTK_KEY_SEND = 65441
FTK_KEY_REPLY = 65442
FTK_KEY_SAVE = 65443
FTK_KEY_BATTERY = 65444
FTK_KEY_BLUETOOTH = 65445
FTK_KEY_WLAN = 65446
FTK_KEY_POWER = 65447
FTK_KEY_MENU = 65471
FTK_KEY_CHOOSE_IME = 65473

# enum from fontdata.h
# enum _Encoding
(ENC_UTF16,
	ENC_ANSI) = range(0, 2)

# constants from ftk_input_method.h
FTK_IM_MAX_CANDIDATES = 20

# enum from ftk_input_method.h
# enum _FtkInputType
(FTK_INPUT_NORMAL,
	FTK_INPUT_DIGIT,
	FTK_INPUT_ALPHA,
	FTK_INPUT_URL,
	FTK_INPUT_EMAIL,
	FTK_INPUT_ALL) = range(0, 6)

# constants from ftk_display.h
FTK_DISPLAY_LISTENER_NR = 16

# constants from ftk_text_layout.h
FTK_LINE_CHAR_NR = 255

# enum from ftk_text_layout.h
# enum _FtkTextAttr
FTK_TEXT_ATTR_NORMAL = 0
FTK_TEXT_ATTR_SHAPED = 1
FTK_TEXT_ATTR_EXTENDED = 2
FTK_TEXT_ATTR_STANDARD = 4
FTK_TEXT_ATTR_RTOL = 8

# enum from ftk_event.h
# enum _FtkEventType
(FTK_EVT_NOP,
	FTK_EVT_IDLE,
	FTK_EVT_INIT,
	FTK_EVT_TIMER,
	FTK_EVT_QUIT,
	FTK_EVT_KEY_UP,
	FTK_EVT_KEY_DOWN,
	FTK_EVT_MOUSE_MOVE,
	FTK_EVT_MOUSE_DOWN,
	FTK_EVT_MOUSE_LONG_PRESS,
	FTK_EVT_KEY_LONG_PRESS,
	FTK_EVT_MOUSE_UP,
	FTK_EVT_HIDE,
	FTK_EVT_SHOW,
	FTK_EVT_MAP,
	FTK_EVT_UNMAP,
	FTK_EVT_UPDATE,
	FTK_EVT_MOVE,
	FTK_EVT_RESIZE,
	FTK_EVT_MOVE_RESIZE,
	FTK_EVT_FOCUS_IN,
	FTK_EVT_FOCUS_OUT,
	FTK_EVT_ADD_CHILD,
	FTK_EVT_IM_COMMIT,
	FTK_EVT_IM_PREEDIT,
	FTK_EVT_SET_TEXT,
	FTK_EVT_GET_TEXT,
	FTK_EVT_IM_ACT_COMMIT,
	FTK_EVT_OS_IM_COMMIT,
	FTK_EVT_REMOVE_CHILD,
	FTK_EVT_WND_DESTROY,
	FTK_EVT_RELAYOUT_WND,
	FTK_EVT_ADD_SOURCE,
	FTK_EVT_REMOVE_SOURCE,
	FTK_EVT_THEME_CHANGED,
	FTK_EVT_SCREEN_ROTATED,
	FTK_EVT_DISABLE_CURSOR,
	FTK_EVT_ENABLE_CURSOR,
	FTK_EVT_OS_SCREEN_ROTATED,
	FTK_EVT_LOCALE_CHANGED,
	FTK_EVT_DISPLAY_CHANGED,
	FTK_EVT_TOP_WND_CHANGED,
	FTK_EVT_WND_CONFIG_CHANGED) = range(0, 43)

# constants from ftk_xml_parser.h
MAX_ATTR_NR = 48

# constants from ftk_message_box.h
FTK_MSGBOX_MAX_BUTTONS = 3

# enum from ftk_gc.h
# enum _FtkGcMask
FTK_GC_BG = 1
FTK_GC_FG = 2
FTK_GC_FONT = 4
FTK_GC_ALPHA = 8
FTK_GC_BITMAP = 16
FTK_GC_LINE_MASK = 32
#END GENERATED CONSTANTS


#BEGIN MANULLY-INSERTED CONSTANTS

# From ftk_widget.h
FTK_WIDGET_SUBCLASS_NR = 5

# From ftk_sources_manager.c
FTK_MIN_SOURCE_NR = 32

#END MANUALLY-INSERTED CONSTANTS
